# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-27 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirmResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_id', models.IntegerField()),
                ('firm_type', models.CharField(choices=[('RawFirm', 'Фірма-виробник сировини'), ('ProductionFirm', 'Фірма-виробник споживчої продукції'), ('CapitalFirm', 'Фірма-виробник капіталу')], max_length=1024)),
                ('decision_maker_type', models.CharField(max_length=1024, verbose_name=(('intuitive', 'Інтуїтивний метод'), ('extrapolation', 'Метод екстраполяції тенденції'), ('moses', 'Метод маржі прибутку'), ('random', 'Випадковий вибір'), ('rational', 'Раціональний вибір'), ('nonconscious', 'Несвідоме навчання'), ('qlearning', 'Q-навчання'), ('budget', 'Метод оптимального розподілу часток бюджету'), ('hierarchical', 'Ієрархічна база правил'), ('lcs', 'Система лінійних класифікаторів'), ('regression_decision_tree', 'Регресійне дерево рішень'), ('perceptron', 'Одношаровий персептрон'), ('svm', 'Система опорних векторів'), ('classification_decision_tree', 'Класифікаційне дерево рішень')))),
                ('step', models.IntegerField(null=True)),
                ('money', models.FloatField(null=True)),
                ('price', models.FloatField(null=True)),
                ('salary', models.FloatField(null=True)),
                ('sold', models.FloatField(null=True)),
                ('sales', models.FloatField(null=True)),
                ('stock', models.FloatField(null=True)),
                ('profit', models.FloatField(null=True)),
                ('plan', models.IntegerField(null=True)),
                ('labor_capacity', models.IntegerField(null=True)),
                ('total_salary', models.FloatField(null=True)),
                ('salary_budget', models.FloatField(null=True)),
                ('raw', models.FloatField(null=True)),
                ('raw_budget', models.FloatField(null=True)),
                ('raw_need', models.FloatField(null=True)),
                ('raw_expenses', models.FloatField(null=True)),
                ('raw_bought', models.FloatField(null=True)),
                ('capital', models.FloatField(null=True)),
                ('capital_budget', models.FloatField(null=True)),
                ('capital_need', models.FloatField(null=True)),
                ('capital_expenses', models.FloatField(null=True)),
                ('capital_bought', models.FloatField(null=True)),
                ('workers', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FirmRunConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.FloatField(default=1000, verbose_name='Наявні гроші')),
                ('salary', models.FloatField(blank=True, default=20, null=True, verbose_name='Заробітна плата')),
                ('price', models.FloatField(blank=True, default=5, null=True, verbose_name='Ціна')),
                ('plan', models.FloatField(blank=True, null=True, verbose_name='Плановий обсяг виробництва')),
                ('salary_budget', models.FloatField(blank=True, null=True, verbose_name='Бюджет на оплату праці')),
                ('labor_capacity', models.FloatField(blank=True, null=True, verbose_name='Планова кількість працівників')),
                ('demand_elasticity', models.FloatField(default=-5, verbose_name='Еластичність попиту на продукцію')),
                ('labor_productivity', models.FloatField(default=50, verbose_name='Продуктивність праці')),
                ('raw_productivity', models.FloatField(blank=True, null=True, verbose_name='Продуктивність сировини')),
                ('raw_need', models.FloatField(blank=True, null=True, verbose_name='Потреба в сировині')),
                ('raw_budget', models.FloatField(blank=True, null=True, verbose_name='Бюджет на закупівлю сировини')),
                ('raw', models.FloatField(blank=True, null=True, verbose_name='Початкові запаси сировини')),
                ('capital_productivity', models.FloatField(blank=True, null=True, verbose_name='Продуктивність капіталу')),
                ('capital_need', models.FloatField(blank=True, null=True, verbose_name='Потреба в капіталі')),
                ('capital_budget', models.FloatField(blank=True, null=True, verbose_name='Бюджет на закупівлю капіталу')),
                ('capital_expenses', models.FloatField(blank=True, null=True, verbose_name='Інвестиції в капітал')),
                ('capital', models.FloatField(blank=True, null=True, verbose_name='Початкові запаси капіталу')),
                ('capital_amortization', models.FloatField(blank=True, null=True, verbose_name='Амортизація капіталу')),
            ],
        ),
        migrations.CreateModel(
            name='FirmStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('raw_firm', 'Виробник сировини'), ('capital_firm', 'Виробник капіталу'), ('production_firm', 'Виробник споживчої продукції')], default='production_firm', max_length=1024, verbose_name='Тип фірми')),
                ('salary', models.BooleanField(default=True, verbose_name='Заробітна платна')),
                ('price', models.BooleanField(default=True, verbose_name='Ціна')),
                ('labor_capacity', models.BooleanField(default=False, verbose_name='Планова кількість працівників')),
                ('plan', models.BooleanField(default=False, verbose_name='Плановий обсяг виробництва')),
                ('salary_budget', models.BooleanField(default=False, verbose_name='Бюджет на оплату праці')),
                ('raw_need', models.NullBooleanField(default=None, verbose_name='Потреба в сировині')),
                ('raw_budget', models.NullBooleanField(default=None, verbose_name='Бюджет на закупівлю сировини')),
                ('capital_need', models.NullBooleanField(default=None, verbose_name='Потреба в капіталі')),
                ('capital_budget', models.NullBooleanField(default=None, verbose_name='Бюджет на закупівлю капіталу')),
            ],
        ),
        migrations.CreateModel(
            name='GoodMarketResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField(null=True)),
                ('seller_id', models.IntegerField(null=True)),
                ('buyer_id', models.IntegerField(null=True)),
                ('quantity', models.FloatField(null=True)),
                ('money', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GovernmentRunConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_tax', models.FloatField(null=True, verbose_name='Податок на доходи фізичних осіб')),
                ('profit_tax', models.FloatField(null=True, verbose_name='Податок на прибуток')),
                ('import_tax', models.FloatField(null=True, verbose_name='Ввізне мито')),
                ('coefficient_help', models.FloatField(null=True, verbose_name='Коефіцієнт розрахунку допомоги по безробіттю')),
                ('minimal_help', models.FloatField(null=True, verbose_name='Мінімальна допомога по безробіттю')),
            ],
        ),
        migrations.CreateModel(
            name='GovernmentStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_tax', models.NullBooleanField(default=None, verbose_name='Податок на доходи фізичних осіб')),
                ('profit_tax', models.NullBooleanField(default=None, verbose_name='Податок на прибуток')),
                ('import_tax', models.NullBooleanField(default=None, verbose_name='Ввізне мито')),
                ('coefficient_help', models.NullBooleanField(default=None, verbose_name='Коефіцієнт розрахунку допомоги по безробіттю')),
                ('minimal_help', models.NullBooleanField(default=None, verbose_name='Мінімальна допомога по безробіттю')),
            ],
        ),
        migrations.CreateModel(
            name='HouseholdRunConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=500, null=True, verbose_name='Кількість домогосподарств')),
                ('consumption_need', models.FloatField(null=True, verbose_name='Потреба в споживчій продукції')),
                ('consumption_budget', models.FloatField(null=True, verbose_name='Бюджет на споживання')),
            ],
        ),
        migrations.CreateModel(
            name='HouseholdStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumption_need', models.BooleanField(default=False, verbose_name='Потреба в споживчій продукції')),
                ('consumption_budget', models.BooleanField(default=False, verbose_name='Бюджет на споживання')),
            ],
        ),
        migrations.CreateModel(
            name='LaborMarketResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField(null=True)),
                ('worker_id', models.IntegerField(null=True)),
                ('employer_id', models.IntegerField(null=True)),
                ('action', models.CharField(choices=[('fire', 'fire'), ('hire', 'hire')], max_length=4)),
                ('salary', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Learning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('intuitive', 'Інтуїтивний метод'), ('extrapolation', 'Метод екстраполяції тенденції'), ('moses', 'Метод маржі прибутку'), ('random', 'Випадковий вибір'), ('rational', 'Раціональний вибір'), ('nonconscious', 'Несвідоме навчання'), ('qlearning', 'Q-навчання'), ('budget', 'Метод оптимального розподілу часток бюджету'), ('hierarchical', 'Ієрархічна база правил'), ('lcs', 'Система лінійних класифікаторів'), ('regression_decision_tree', 'Регресійне дерево рішень'), ('perceptron', 'Одношаровий персептрон'), ('svm', 'Система опорних векторів'), ('classification_decision_tree', 'Класифікаційне дерево рішень')], default='random', max_length=1024, verbose_name='Метод навчання')),
                ('count', models.IntegerField(default=0, verbose_name='Кількість фірм такого типу')),
                ('firm_run_configuration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FirmRunConfiguration', to='models.FirmRunConfiguration')),
            ],
        ),
        migrations.CreateModel(
            name='ModelConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('title', models.CharField(max_length=1024, null=True, verbose_name='Назва конфігурації моделі')),
                ('outside_world', models.NullBooleanField(default=None, verbose_name='Зовнішній світ')),
                ('capital_firm_structure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CapitalFirm', to='models.FirmStructure')),
                ('government_structure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.GovernmentStructure')),
                ('household_structure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.HouseholdStructure')),
                ('production_firm_structure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProductionFirm', to='models.FirmStructure')),
                ('raw_firm_structure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RawFirm', to='models.FirmStructure')),
            ],
        ),
        migrations.CreateModel(
            name='ModelResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('model_config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.ModelConfig')),
            ],
        ),
        migrations.CreateModel(
            name='ModelRunConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('iterations', models.IntegerField(default=10, verbose_name='Кількість ітерацій')),
                ('initial_money', models.FloatField(default=100000, verbose_name='Початковий обсяг грошової маси')),
                ('household_birth', models.IntegerField(default=10, verbose_name='Приріст чисельності домогосподарств')),
                ('firm_birth', models.IntegerField(default=0, verbose_name='Рівень появи нових фірм')),
                ('money_growth', models.FloatField(default=2000, verbose_name='Приріст грошової маси')),
                ('capital_firm_config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CapitalFirm', to='models.FirmRunConfiguration')),
                ('government_config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Government', to='models.GovernmentRunConfiguration')),
                ('household_config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Household', to='models.HouseholdRunConfiguration')),
            ],
        ),
        migrations.CreateModel(
            name='ModelVerboseNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.CharField(max_length=1024, verbose_name='Назва таблиці')),
                ('field_name', models.CharField(max_length=1024, verbose_name='Назва поля в базі')),
                ('field_human', models.CharField(max_length=1024, verbose_name='Змістовна назва поля')),
                ('type', models.CharField(choices=[('categorical', 'Категорійна'), ('numerical', 'Числова')], default='categorical', max_length=1024, verbose_name='Тип поля')),
            ],
        ),
        migrations.CreateModel(
            name='OutsideWorldRunConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_price', models.FloatField(null=True, verbose_name='Ціна сировини')),
                ('capital_price', models.FloatField(null=True, verbose_name='Ціна капіталу')),
                ('good_price', models.FloatField(null=True, verbose_name='Ціна споживчого товару')),
                ('exchange_rate', models.FloatField(null=True, verbose_name='Курси обміну валют')),
                ('sell_probability', models.FloatField(null=True, verbose_name='Ймовірність купівлі товару внутрішньої фірми')),
            ],
        ),
        migrations.CreateModel(
            name='WorldResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField(null=True)),
                ('raw_firms', models.IntegerField(null=True)),
                ('capital_firms', models.IntegerField(null=True)),
                ('production_firms', models.IntegerField(null=True)),
                ('households', models.IntegerField(null=True)),
                ('price', models.FloatField(null=True)),
                ('raw_price', models.FloatField(null=True)),
                ('capital_price', models.FloatField(null=True)),
                ('production_price', models.FloatField(null=True)),
                ('salary', models.FloatField(null=True)),
                ('raw_salary', models.FloatField(null=True)),
                ('capital_salary', models.FloatField(null=True)),
                ('production_salary', models.FloatField(null=True)),
                ('sold', models.FloatField(null=True)),
                ('raw_sold', models.FloatField(null=True)),
                ('capital_sold', models.FloatField(null=True)),
                ('production_sold', models.FloatField(null=True)),
                ('stock', models.FloatField(null=True)),
                ('raw_stock', models.FloatField(null=True)),
                ('capital_stock', models.FloatField(null=True)),
                ('production_stock', models.FloatField(null=True)),
                ('sales', models.FloatField(null=True)),
                ('raw_sales', models.FloatField(null=True)),
                ('capital_sales', models.FloatField(null=True)),
                ('production_sales', models.FloatField(null=True)),
                ('money', models.FloatField(null=True)),
                ('raw_money', models.FloatField(null=True)),
                ('capital_money', models.FloatField(null=True)),
                ('production_money', models.FloatField(null=True)),
                ('employed', models.IntegerField(null=True)),
                ('raw_employed', models.IntegerField(null=True)),
                ('capital_employed', models.IntegerField(null=True)),
                ('production_employed', models.IntegerField(null=True)),
                ('labor_capacity', models.IntegerField(null=True)),
                ('raw_labor_capacity', models.IntegerField(null=True)),
                ('capital_labor_capacity', models.IntegerField(null=True)),
                ('production_labor_capacity', models.IntegerField(null=True)),
                ('total_salary', models.FloatField(null=True)),
                ('raw_total_salary', models.FloatField(null=True)),
                ('capital_total_salary', models.FloatField(null=True)),
                ('production_total_salary', models.FloatField(null=True)),
                ('salary_budget', models.FloatField(null=True)),
                ('raw_salary_budget', models.FloatField(null=True)),
                ('capital_salary_budget', models.FloatField(null=True)),
                ('production_salary_budget', models.FloatField(null=True)),
                ('unemployment_rate', models.FloatField(null=True)),
                ('raw', models.FloatField(null=True)),
                ('raw_need', models.FloatField(null=True)),
                ('raw_budget', models.FloatField(null=True)),
                ('raw_expenses', models.FloatField(null=True)),
                ('capital', models.FloatField(null=True)),
                ('capital_need', models.FloatField(null=True)),
                ('capital_budget', models.FloatField(null=True)),
                ('capital_expenses', models.FloatField(null=True)),
                ('model_result', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.ModelResult')),
            ],
        ),
        migrations.AddField(
            model_name='modelrunconfiguration',
            name='outside_world_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OutsideWorld', to='models.OutsideWorldRunConfiguration'),
        ),
        migrations.AddField(
            model_name='modelrunconfiguration',
            name='production_firm_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProductionFirm', to='models.FirmRunConfiguration'),
        ),
        migrations.AddField(
            model_name='modelrunconfiguration',
            name='raw_firm_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RawFirm', to='models.FirmRunConfiguration'),
        ),
        migrations.AddField(
            model_name='modelresult',
            name='model_run_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.ModelRunConfiguration'),
        ),
        migrations.AddField(
            model_name='labormarketresult',
            name='model_result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.ModelResult'),
        ),
        migrations.AddField(
            model_name='goodmarketresult',
            name='model_result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.ModelResult'),
        ),
        migrations.AddField(
            model_name='firmresult',
            name='model_result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.ModelResult'),
        ),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_firmresult', 'model_result','Запуск', 'categorical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_firmresult', 'firm_id','Ід фірми', 'categorical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_firmresult', 'firm_type','Тип фірми', 'categorical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_firmresult', 'decision_maker_type','Тип навчання', 'categorical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_firmresult', 'step','Крок', 'categorical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_firmresult', 'money','Грошові активи', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_firmresult', 'price','Ціна', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_firmresult', 'salary','Зарплата', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_firmresult', 'sold','Обсяг продажів (у натуральних одиницях)', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_firmresult', 'sales','Обсяг продажів (у грошових одиницях)', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_firmresult', 'stock','Запаси', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_firmresult', 'profit','Прибуток', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_firmresult', 'plan','Плановий обсяг виробництва', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_firmresult', 'labor_capacity','Планова кількість працівників', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_firmresult', 'total_salary','Фактичний фонд заробітної плати', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_firmresult', 'salary_budget','Плановий фонд заробітної плати', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_firmresult', 'raw','Запаси сировини', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_firmresult', 'raw_budget','Бюджет на закупівлю сировини', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_firmresult', 'raw_need','Потреба в сировині', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_firmresult', 'raw_expenses','Фактичні витрати на закупівлю сировини', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_firmresult', 'raw_bought','Закуплена сировина', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_firmresult', 'capital','Запаси капіталу', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_firmresult', 'capital_budget','Бюджет на закупівалю капіталу', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_firmresult', 'capital_need','Потреба в капіталі', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_firmresult', 'capital_expenses','Фактичні витрати на закупівлю капіталу', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_firmresult', 'capital_bought','Закуплений капітал', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_firmresult', 'workers','Фактична кількість працівників', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_worldresult', 'model_result ','Запуск', 'categorical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_worldresult', 'step ','Крок', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_worldresult', 'raw_firms ','Кількість виробників сировини', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_worldresult', 'capital_firms ','Кількість виробників капіталу', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_worldresult', 'production_firms ','Кількість виробників споживчих товарів', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_worldresult', 'households ','Кількість домогосподарств', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_worldresult', 'price ','Середня ціна', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_worldresult', 'raw_price ','Середня ціна сировини', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_worldresult', 'capital_price ','Середня ціна капіталу', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_worldresult', 'production_price ','Середня ціна споживчих товарів', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_worldresult', 'salary ','Середня заробітна плата', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_worldresult', 'raw_salary ','Середня заробітна плата у виробників сировини', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_worldresult', 'capital_salary ','Середня заробітна плата у виробників капіталу', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_worldresult', 'production_salary ','Середня заробітна плата у виробників споживчої продукції', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_worldresult', 'sold ','Обсяг продажів (у натуральних одиницях)', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_worldresult', 'raw_sold ','Обсяг продажів сировини (у натуральних одиницях)', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_worldresult', 'capital_sold ','Обсяг продажів капіталу (у натуральних одиницях)', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_worldresult', 'production_sold ','Обсяг продажів споживчих товарів (у натуральних одиницях)', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_worldresult', 'stock ','Запаси (у натуральних одиницях)', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_worldresult', 'raw_stock ','Запаси сировини (у натуральних одиницях)', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_worldresult', 'capital_stock ','Запаси капіталу (у натуральних одиницях)', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_worldresult', 'production_stock ','Запаси споживчих товарів (у натуральних одиницях)', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_worldresult', 'sales ','Обсяг продажів (у грошових одиницях)', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_worldresult', 'raw_sales ','Обсяг продажів сировини (у грошових одиницях)', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_worldresult', 'capital_sales ','Обсяг продажів капіталу (у грошових одиницях)', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_worldresult', 'production_sales ','Обсяг продажів споживчих товарів (у грошових одиницях)', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_worldresult', 'money ','Грошові активи', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_worldresult', 'raw_money ','Грошові активи виробників сировини', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_worldresult', 'capital_money ','Грошові активи виробників капіталу', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_worldresult', 'production_money ','Грошові активи виробників споживчих товарів', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_worldresult', 'employed ','Кількість зайнятих', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_worldresult', 'raw_employed ','Кількість зайнятих у виробництві сировини', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_worldresult', 'capital_employed ','Кількість зайнятих у виробництві капіталу', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_worldresult', 'production_employed ','Кількість зайнятих у виробництві споживчої продукції', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_worldresult', 'labor_capacity ','Планова кількість працівників', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_worldresult', 'raw_labor_capacity ','Планова кількість працівників на виробництві сировини', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_worldresult', 'capital_labor_capacity ','Планова кількість працівників на виробництві капіталу', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_worldresult', 'production_labor_capacity ','Планова кількість працівників на виробництві споживчих товарів', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_worldresult', 'total_salary ','Загальний фонд заробітної плати', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_worldresult', 'raw_total_salary ','Загальний фонд заробітної плати у виробників сировини', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_worldresult', 'capital_total_salary ','Загальний фонд заробітної плати у виробників капіталу', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_worldresult', 'production_total_salary ','Загальний фонд заробітної плати у виробників споживчої продукції', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_worldresult', 'salary_budget ','Плановий фонд оплати праці', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_worldresult', 'raw_salary_budget ','Плановий фонд оплати праці у виробників сировини', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_worldresult', 'capital_salary_budget ','Плановий фонд оплати праці у виробників капіталу', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_worldresult', 'production_salary_budget ','Плановий фонд оплати праці у виробників споживчої продукції', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_worldresult', 'unemployment_rate ','Рівень безробіття', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_worldresult', 'raw ','Загальний обсяг використання сировини (у натуральних одиницях)', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_worldresult', 'raw_need ','Потреба в сировині', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_worldresult', 'raw_budget ','Плановий обсяг витрат на закупівлю сировини', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_worldresult', 'raw_expenses ','Фактичні витрати на закупівлю сировини', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_worldresult', 'capital ','Загальний обсяг використання капіталу (у натуральних одиницях)', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_worldresult', 'capital_need ','Потреба в капіталі', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_worldresult', 'capital_budget ','Плановий обсяг витрат на закупівлю капіталу', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_worldresult', 'capital_expenses ','Фактичні витрати на закупівлю капіталу', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_goodmarketresult', 'model_result ','Запуск', 'categorical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_goodmarketresult', 'step ','Крок', 'categorical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_goodmarketresult', 'seller_id ','Ід продавця', 'categorical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_goodmarketresult', 'buyer_id ','Ід покупця', 'categorical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_goodmarketresult', 'quantity ','Величина транзакції у натуральних одиницях', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_worldresult', 'money ','Величина транзакції у грошових одиницях', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_labormarketresult', 'model_result ','Запуск', 'categorical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_labormarketresult', 'step ','Крок', 'categorical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_labormarketresult', 'worker_id ','Ід робітника', 'categorical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_labormarketresult', 'employer_id ','Ід наймача', 'categorical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_labormarketresult', 'action ','Дія', 'categorical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_labormarketresult', 'salary ','Заробітна плата', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_governmentresult', 'model_result','Запуск', 'categorical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_governmentresult', 'step','Крок', 'categorical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_governmentresult', 'participant_id','Ід учасника транзація', 'categorical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_governmentresult', 'action','Дія', 'categorical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_governmentresult', 'money','Величина транзакції у грошових одиницях', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_outsideworldresult', 'model_result','Запуск', 'categorical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_outsideworldresult', 'step','Крок', 'categorical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_outsideworldresult', 'raw_price','Ціна сировини', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_outsideworldresult', 'capital_price','Ціна капіталу', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_outsideworldresult', 'production_price','Ціна споживчого товару', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_outsideworldresult', 'raw_sales','Обсяги продажів сировини у грошових одиницях', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_outsideworldresult', 'capital_sales','Обсяги продажів капіталу у грошових одиницях', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_outsideworldresult', 'production_sales','Обсяги продажу споживчої продукції у грошових одиницях', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_outsideworldresult', 'raw_sold','Обсяги продажу сировини у натуральних одиницях', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_outsideworldresult', 'capital_sold','Обсяги продажу капіталу у натуральних одиницях', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_outsideworldresult', 'production_sold','Обсяги продажу споживчої продукції у натуральних одиницях', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_outsideworldresult', 'raw_expenses','Витрати на закупівлю сировини', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_outsideworldresult', 'capital_expenses','Витрати на закупівлю капіталу', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_outsideworldresult', 'production_expenses','Витрати на закупівлю споживчої продукції', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_outsideworldresult', 'raw_bought','Закуплена сировина', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_outsideworldresult', 'capital_bought','Закуплений капітал', 'numerical')"),
        migrations.RunSQL(
            "INSERT INTO models_modelverbosenames(`table`, field_name, field_human, type) VALUES('models_outsideworldresult', 'production_bought','Закуплена споживча продукція', 'numerical')"),

    ]
