# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure_firms_producers', models.BooleanField(verbose_name='Фірми-виробники споживчої продукції')),
                ('structure_households', models.BooleanField(verbose_name='Домогосподарства')),
                ('structure_firms_capital', models.BooleanField(verbose_name='Фірми-виробники капіталу')),
                ('structure_firms_raw', models.BooleanField(verbose_name='Фірми-виробники сировини')),
                ('structure_government', models.BooleanField(verbose_name='Держава')),
                ('structure_outside_world', models.BooleanField(verbose_name='Зовнішній світ')),
            ],
        ),
    ]
