# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirmStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('raw_firm', 'Виробник сировини'), ('capital_firm', 'Виробник капіталу'), ('production_firm', 'Виробник споживчої продукції')], default='production_firm', max_length=1024, verbose_name='Тип фірми')),
                ('salary', models.BooleanField(default=False, verbose_name='Заробітна платна')),
                ('price', models.BooleanField(default=False, verbose_name='Ціна')),
                ('workers_count', models.BooleanField(default=False, verbose_name='Планова кількість працівників')),
                ('plan', models.BooleanField(default=False, verbose_name='Плановий обсяг виробництва')),
                ('salary_budget', models.BooleanField(default=False, verbose_name='Бюджет на оплату праці')),
                ('raw_need', models.BooleanField(default=False, verbose_name='Потреба в сировині')),
                ('raw_budget', models.BooleanField(default=False, verbose_name='Бюджет на закупівлю сировини')),
                ('capital_need', models.BooleanField(default=False, verbose_name='Потреба в капіталі')),
                ('capital_budget', models.BooleanField(default=False, verbose_name='Бюджет на закупівлю капіталу')),
            ],
        ),
        migrations.CreateModel(
            name='GovernmentStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_tax', models.BooleanField(default=False, verbose_name='Податок на доходи фізичних осіб')),
                ('profit_tax', models.BooleanField(default=False, verbose_name='Податок на прибуток')),
                ('import_tax', models.BooleanField(default=False, verbose_name='Ввізне мито')),
                ('coefficient_help', models.BooleanField(default=False, verbose_name='Коефіцієнт розрахунку допомоги по безробіттю')),
                ('minimal_tax', models.BooleanField(default=False, verbose_name='Мінімальна допомога по безробіттю')),
            ],
        ),
        migrations.CreateModel(
            name='HouseholdStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumption_need', models.BooleanField(default=False, verbose_name='Потреба в споживчій продукції')),
                ('consumption_budget', models.BooleanField(default=False, verbose_name='Бюджет на споживання')),
            ],
        ),
        migrations.CreateModel(
            name='Learning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('intuitive', 'Інтуїтивний метод'), ('extrapolation', 'Метод екстраполяції тенденції'), ('moses', 'Метод маржі прибутку'), ('random', 'Випадковий вибір'), ('rational', 'Раціональний вибір'), ('nonconscious', 'Несвідоме навчання'), ('qlearning', 'Q-навчання'), ('hierarchical', 'Ієрархічна база правил'), ('lcs', 'Система лінійних класифікаторів'), ('regression_decision_tree', 'Регресійне дерево рішень'), ('perceptron', 'Одношаровий персептрон'), ('svm', 'Система опорних векторів'), ('classification_decision_tree', 'Класифікаційне дерево рішень')], default='random', max_length=1024, verbose_name='Метод навчання')),
                ('count', models.IntegerField(verbose_name='Кількість фірм такого типу')),
            ],
        ),
        migrations.CreateModel(
            name='ModelConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('title', models.CharField(max_length=1024, null=True)),
                ('outside_world', models.BooleanField(default=False, verbose_name='Зовнішній світ')),
                ('capital_firm_structure_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CapitalFirm', to='models.FirmStructure')),
                ('government_structure_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.GovernmentStructure')),
                ('household_structure_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.HouseholdStructure')),
                ('production_firm_structure_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProductionFirm', to='models.FirmStructure')),
                ('raw_firm_structure_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RawFirm', to='models.FirmStructure')),
            ],
        ),
        migrations.CreateModel(
            name='ModelResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modelConfig', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.ModelConfig')),
            ],
        ),
        migrations.CreateModel(
            name='ModelRunConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='modelresult',
            name='modelRunConfiguration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.ModelRunConfiguration'),
        ),
        migrations.AddField(
            model_name='firmstructure',
            name='learning',
            field=models.ManyToManyField(to='models.Learning'),
        ),
    ]
