# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelconfig',
            name='firm_parameters_price',
            field=models.BooleanField(default=False, verbose_name='Ціна'),
        ),
        migrations.AddField(
            model_name='modelconfig',
            name='firm_parameters_salary',
            field=models.BooleanField(default=False, verbose_name='Заробітна платна'),
        ),
        migrations.AddField(
            model_name='modelconfig',
            name='firm_parameters_salary_budget',
            field=models.BooleanField(default=False, verbose_name='Бюджет на оплату праці'),
        ),
        migrations.AddField(
            model_name='modelconfig',
            name='firm_parameters_workers_count',
            field=models.BooleanField(default=False, verbose_name='Планова кількість працівників'),
        ),
        migrations.AlterField(
            model_name='modelconfig',
            name='structure_firms_capital',
            field=models.BooleanField(default=False, verbose_name='Фірми-виробники капіталу'),
        ),
        migrations.AlterField(
            model_name='modelconfig',
            name='structure_firms_producers',
            field=models.BooleanField(default=True, verbose_name='Фірми-виробники споживчої продукції'),
        ),
        migrations.AlterField(
            model_name='modelconfig',
            name='structure_firms_raw',
            field=models.BooleanField(default=False, verbose_name='Фірми-виробники сировини'),
        ),
        migrations.AlterField(
            model_name='modelconfig',
            name='structure_government',
            field=models.BooleanField(default=False, verbose_name='Держава'),
        ),
        migrations.AlterField(
            model_name='modelconfig',
            name='structure_households',
            field=models.BooleanField(default=True, verbose_name='Домогосподарства'),
        ),
        migrations.AlterField(
            model_name='modelconfig',
            name='structure_outside_world',
            field=models.BooleanField(default=False, verbose_name='Зовнішній світ'),
        ),
    ]
