# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-02 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField(null=True)),
                ('participant_id', models.IntegerField(null=True)),
                ('action', models.CharField(max_length=1024, null=True)),
                ('money', models.FloatField(null=True)),
                ('model_result', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.ModelResult')),
            ],
        ),
        migrations.CreateModel(
            name='OutsideWorldResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField(null=True)),
                ('raw_price', models.FloatField(null=True)),
                ('capital_price', models.FloatField(null=True)),
                ('production_price', models.FloatField(null=True)),
                ('raw_sales', models.FloatField(null=True)),
                ('capital_sales', models.FloatField(null=True)),
                ('production_sales', models.FloatField(null=True)),
                ('raw_sold', models.FloatField(null=True)),
                ('capital_sold', models.FloatField(null=True)),
                ('production_sold', models.FloatField(null=True)),
                ('raw_expenses', models.FloatField(null=True)),
                ('capital_expenses', models.FloatField(null=True)),
                ('production_expenses', models.FloatField(null=True)),
                ('raw_bought', models.FloatField(null=True)),
                ('capital_bought', models.FloatField(null=True)),
                ('production_bought', models.FloatField(null=True)),
                ('model_result', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.ModelResult')),
            ],
        ),
        migrations.AddField(
            model_name='governmentrunconfiguration',
            name='money',
            field=models.FloatField(null=True, verbose_name='Грошові активи'),
        ),
        migrations.AlterField(
            model_name='goodmarketresult',
            name='buyer_id',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='goodmarketresult',
            name='seller_id',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
