# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-02 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_auto_20171102_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmresult',
            name='firm_type',
            field=models.CharField(choices=[('ProductionFirm', 'Фірма-виробник споживчої продукції'), ('CapitalFirm', 'Фірма-виробник капіталу'), ('RawFirm', 'Фірма-виробник сировини')], max_length=1024),
        ),
    ]
