# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_auto_20170709_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
