# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_modelresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelRunConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='modelconfig',
            name='title',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='modelresult',
            name='modelConfig',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.ModelConfig'),
        ),
        migrations.AddField(
            model_name='modelresult',
            name='modelRunConfiguration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.ModelRunConfiguration'),
        ),
    ]
