# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_auto_20170722_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='householdrunconfiguration',
            name='consumption_budget',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Бюджет на споживання'),
        ),
        migrations.AlterField(
            model_name='modelrunconfiguration',
            name='initial_money',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Початковий обсяг грошової маси'),
        ),
        migrations.AlterField(
            model_name='modelrunconfiguration',
            name='money_growth',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Приріст грошової маси-'),
        ),
        migrations.AlterField(
            model_name='outsideworldrunconfiguration',
            name='capital_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Ціна капіталу'),
        ),
        migrations.AlterField(
            model_name='outsideworldrunconfiguration',
            name='good_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Ціна споживчого товару'),
        ),
        migrations.AlterField(
            model_name='outsideworldrunconfiguration',
            name='raw_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Ціна сировини'),
        ),
    ]
