# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_auto_20170722_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='householdrunconfiguration',
            name='count',
            field=models.IntegerField(null=True, verbose_name='Кількість домогосподарств'),
        ),
    ]
