# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_auto_20170722_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firmrunconfiguration',
            name='learning_method',
        ),
        migrations.AddField(
            model_name='learning',
            name='firm_run_configuration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FirmRunConfiguration', to='models.FirmRunConfiguration'),
        ),
    ]
