# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_auto_20170730_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmrunconfiguration',
            name='capital_amortization',
            field=models.FloatField(blank=True, null=True, verbose_name='Амортизація капіталу'),
        ),
        migrations.AlterField(
            model_name='firmrunconfiguration',
            name='capital_productivity',
            field=models.FloatField(blank=True, null=True, verbose_name='Продуктивність капіталу'),
        ),
        migrations.AlterField(
            model_name='firmrunconfiguration',
            name='demand_elasticity',
            field=models.FloatField(blank=True, null=True, verbose_name='Еластичність попиту на продукцію'),
        ),
        migrations.AlterField(
            model_name='firmrunconfiguration',
            name='labor_productivity',
            field=models.FloatField(blank=True, null=True, verbose_name='Продуктивність праці'),
        ),
        migrations.AlterField(
            model_name='firmrunconfiguration',
            name='raw_productivity',
            field=models.FloatField(blank=True, null=True, verbose_name='Продуктивність сировини'),
        ),
    ]
