# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0010_auto_20170730_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learning',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Кількість фірм такого типу'),
        ),
    ]
