# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-26 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0010_auto_20170730_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalFirmRunConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demand_elasticity', models.FloatField(blank=True, null=True, verbose_name='Еластичність попиту на продукцію')),
                ('labor_productivity', models.FloatField(blank=True, null=True, verbose_name='Продуктивність праці')),
                ('raw_productivity', models.FloatField(blank=True, null=True, verbose_name='Продуктивність сировини')),
            ],
        ),
        migrations.CreateModel(
            name='RawFirmRunConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demand_elasticity', models.FloatField(blank=True, null=True, verbose_name='Еластичність попиту на продукцію')),
                ('labor_productivity', models.FloatField(blank=True, null=True, verbose_name='Продуктивність праці')),
            ],
        ),
        migrations.RenameModel(
            old_name='FirmRunConfiguration',
            new_name='ProductionFirmRunConfiguration',
        ),
        migrations.RemoveField(
            model_name='learning',
            name='firm_run_configuration',
        ),
        migrations.RemoveField(
            model_name='modelrunconfiguration',
            name='firm_config',
        ),
        migrations.AddField(
            model_name='modelrunconfiguration',
            name='production_firm_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProductionFirm', to='models.ProductionFirmRunConfiguration'),
        ),
        migrations.AddField(
            model_name='modelrunconfiguration',
            name='capital_firm_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CapitalFirm', to='models.CapitalFirmRunConfiguration'),
        ),
        migrations.AddField(
            model_name='modelrunconfiguration',
            name='raw_firm_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RawFirm', to='models.RawFirmRunConfiguration'),
        ),
    ]
